spring:
  data:
    mongodb:
      uri:
        mongodb://localhost:27017/spring_boot
  thymeleaf:
    reactive:
      max-chunk-size:
        1024
      chunked-mode-view-names:
        listar-chunked,*chunked*

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8999/eureka
    instance:
      preferIpAddress: true