spring:
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

      properties:
        spring.json.type.mapping : "MovementRegister:com.bank.movement.models.documents.MovementRegister,
        ResponseTransference:com.bank.transference.models.kafka.ResponseTransference,
        RequestWallet:com.bank.wallet.models.kafka.RequestWallet,
        RequestYanki:com.bank.yanki.models.kafka.RequestYanki"
        spring.json.trusted.packages: "*"
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties.spring.json.type.mapping : "MovementRegister:com.bank.payment.models.documents.MovementRegister,
      ResponseTransference:com.bank.wallet.models.kafka.ResponseTransference,
      ResponseTransference:com.bank.yanki.models.kafka.ResponseTransference,
      RequestWallet:com.bank.transference.models.kafka.RequestWallet,
      RequestYanki:com.bank.transference.models.kafka.RequestYanki"