spring:
  data:
    mongodb:
    uri:
      mongodb:
        host:
          localhost
        port:
          27017
        database:
          spring_boot

  thymeleaf:
    reactive:
      max-chunk-size:
        1024
      chunked-mode-view-names:
        listar-chunked,*chunked*
server:
  port:
    8081